---
root: true
parser: '@typescript-eslint/parser'
parserOptions:
  tsconfigRootDir: './'
  project: ['./tsconfig.json']
  ecmaVersion: 'latest'
  sourceType: 'module'

env:
  es2022: true

settings:
  react:
    version: 'detect'

plugins:
  - '@typescript-eslint'
  - 'react'
  - 'react-native'
  - 'unicorn'
  - 'prettier'

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'plugin:react/recommended'
  - 'plugin:react/jsx-runtime'
  - 'plugin:unicorn/recommended'
  - 'plugin:prettier/recommended'
