---
root: true
parser: '@typescript-eslint/parser'
parserOptions:
  tsconfigRootDir: ./
  project: ['./tsconfig.json']

env:
  es6: true

settings:
  react:
    version: detect

plugins:
  - '@typescript-eslint'
  - 'react'
  - 'react-native'

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'plugin:react/recommended'
  - 'plugin:react/jsx-runtime'
  - 'prettier'
